version: '3.8'

services:
  stock-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY:-demo}
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./app:/app/app  # For development hot reload